
Tensor
==========================

Di Pytorch, tensor digunakan untuk input, output, dan parameter dari sebuah model
Tensor memiliki kelebihan dibanding `NumPy <https://numpy.org/>` dalam 2 hal:
1. Operasi Tensor dapat dihitung melalui GPU
2. Tensor dapat melakukan diferensiasi otomatis (dibahas di pertemuan berikutnya)


In [1]:
import torch
import math
import numpy as np

**Inisiasi sebuah Tensor**

Tensor dapat diinisiasi melalui beragam cara

**Langsung dari data**

Tensor dapat diciptakan langsung dari data


In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**Dari sebuah NumPy array**

Tensor dapat diciptakan langsung dari Numpy arrays (dan sebaliknya)



In [4]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


**Dari Tensor yang lain:**

Tensor yang baru akan memiliki sifat (shape, datatype) dari tensor sebelumnya, kecuali secara explicit diganti.



In [5]:
x_ones = torch.ones_like(x_data) # mempertahankan sifat x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # mengganti dtype x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6909, 0.6557],
        [0.5830, 0.7659]]) 



**Dari sebuah angka random atau konstanta:**

``shape`` adalah sebuah tuple dari dimensi tensor. Itu akan menentukan dimensi dari tensor output pada fungsi di bawah ini.



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3454, 0.0758, 0.8690],
        [0.1708, 0.6566, 0.6732]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




**Attributes of a Tensor**

Atribut Tensor akan menjelaskan bentuk, tipe data, dan perangkat penyimpanan tensor



In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




**Operasi pada Tensor**

Terdapat lebih dari 100 operasi tensor (termasuk aritmatika, aljabar linear, manipulasi matriks, dan lainnya), dijelaskan secara lebih komprehensif `disini <https://pytorch.org/docs/stable/torch.html>`

Setiap operasi ini dapat dioperasikan di GPU. Jika menggunakan Colab, alokasikan sebuah GPU melalui Runtime > Change runtime type > GPU

Secara bawaan, tensor diciptakan pada CPU. Kita harus memindahkan tensor ke GPU menggunakan metode ``.to`` (setelah memeriksa ketersediaan GPU). Memindahkan tensor besar antar perangkat, dapat memakan waktu dan memori yang banyak (jadi rencanakanlah secara hati-hati !!!)


In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('Bisa GPU')
    tensor = tensor.to('cuda')
else:
    print('Hanya bisa CPU')

Hanya bisa CPU


Coba beberapa operasi dari daftar.



**Operasi standard yang mirip numpy untuk indexing dan slicing:**



In [9]:
tensor = torch.ones(4, 4)
print('Baris pertama: ', tensor[0])
print('Kolom pertama: ', tensor[:, 0])
print('Kolom terakhir:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

Baris pertama:  tensor([1., 1., 1., 1.])
Kolom pertama:  tensor([1., 1., 1., 1.])
Kolom terakhir: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Menyatukan beberapa tensor** 

Gunakan ``torch.cat`` untuk concatenate beberapa tensor secara pilihan dimensi.
Alternatif lain, `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,



In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Operasi Aritmatika**



In [14]:
# Menghitung perkalian matriks antara 2 tensors. y1, y2, y3 akan memiliki nilai yang sama
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
print(torch.matmul(tensor, tensor.T, out=y3))

# Menghitung perkalian elemen. z1, z2, z3 akan memiliki nilai yang sama
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**tensor 1-elemen** Jika memiliki sebuah tensor 1-elemen (contoh: agregat semua nilai dari sebuah tensor menjadi 1 angka), itu dapat diubah menjadi python numerik menggunakan ``item()``:



In [15]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

tensor(12.) 12.0 <class 'float'>


**Operasi In-Place**

Operasi yang menyimpan hasil kedalam variabel itu sendiri disebut in-place. Mereka menggunakan imbuhan ``_``

contoh: ``x.copy_(y)``, ``x.t_()``, akan merubah ``x``.



In [16]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div class="alert alert-info"><h4>Catatan</h4><p>Operasi In-place dapat menimbulkan masalah ketika menghitung turunan karena kehilangan sejarah operasi. Jadi penggunaan seperti ini kurang dianjurkan.</p></div>



--------------




**Jembatan dengan Numpy**

Tensor pada CPU dan Numpy array dapat menggunakan lokasi memori yang sama,
merubah yang satu akan merubah yang lain




Tensor menjadi NumPy array



In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Perubahan pada tensor terjadi pada Numpy array.



In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array menjadi Tensor



In [21]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")


n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Perubahan pada Numpy array terjadi pada Tensor.



In [22]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


**Matematika dan Logika dengan Tensor**

In [23]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [24]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


**Tensor Broadcasting**

Aturan Broadcasting:
- Masing-masing tensor paling sedikit harus memiliki 1 dimensi
- Membandingkan dimensi dari 2 tensors, dari yang akhir ke yang pertama:
    - Masing-masing dimensi harus sama, atau
    - Salah satu dimensi harus ukuran 1, atau
    - Dimensi tidak eksis di salah satu tensor


In [27]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)
print(rand.shape)
print(torch.ones(1, 4).shape)
print(rand)
print(doubled)

torch.Size([2, 4])
torch.Size([1, 4])
tensor([[0.8980, 0.7317, 0.0827, 0.7186],
        [0.8118, 0.7975, 0.5899, 0.4489]])
tensor([[1.7961, 1.4634, 0.1655, 1.4373],
        [1.6235, 1.5950, 1.1799, 0.8979]])


In [29]:
a =     torch.ones(4, 3, 2)
print(a)

b = a * torch.rand(   3, 2) # dimensi ke 3 dan 2 identik dengan a, # dimensi ke 1 absen
print(b)

c = a * torch.rand(   3, 1) # dimensi ke 3 = 1, # dimensi ke 2 identik dengan a
print(c)

d = a * torch.rand(   1, 2) # dimensi ke 3 identik dengan a, # dimensi ke 2 = 1
print(d)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.1982, 0.4389],
         [0.6325, 0.6314],
         [0.0051, 0.1614]],

        [[0.1982, 0.4389],
         [0.6325, 0.6314],
         [0.0051, 0.1614]],

        [[0.1982, 0.4389],
         [0.6325, 0.6314],
         [0.0051, 0.1614]],

        [[0.1982, 0.4389],
         [0.6325, 0.6314],
         [0.0051, 0.1614]]])
tensor([[[0.6412, 0.6412],
         [0.9038, 0.9038],
         [0.9810, 0.9810]],

        [[0.6412, 0.6412],
         [0.9038, 0.9038],
         [0.9810, 0.9810]],

        [[0.6412, 0.6412],
         [0.9038, 0.9038],
         [0.9810, 0.9810]],

        [[0.6412, 0.6412],
         [0.9038, 0.9038],
         [0.9810, 0.9810]]])
tensor([[[0.9685, 0.9766],
         [0.9685, 0.9766],
         [0.9685, 0.9766]],

        [[0.9685,

**Matematika Tensor Lanjutan**

In [30]:
# fungsi umum
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# fungsi trigonometri dan inversnya
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSin and arcsin:')
print(angles)
print(sines)
print(inverses)

# operasi bitwise
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# perbandingan:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # pembanding
print(torch.eq(d, e)) # returns sebuah tensor tipe bool

# aggregasi:
print('\nAggregate ops:')
print(torch.max(d))        # returns sebuah 1-elemen tensor
print(torch.max(d).item()) # mengeluarkan nilai dari tensor
print(torch.mean(d))       # rata-rata
print(torch.std(d))        # standard deviasi
print(torch.prod(d))       # perkalian semua angka
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter elemen unik

# vektor dan aljabar linear
v1 = torch.tensor([1., 0., 0.])         # unit vektor x
v2 = torch.tensor([0., 1., 0.])         # unit vektor y
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # 3x I

print('\nVektor & Matriks:')
print(torch.cross(v2, v1)) # -ve dari unit vektor z (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3x m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.0886, 0.8073, 0.6018, 0.8838],
        [0.5868, 0.4310, 0.8890, 0.5328]])
tensor([[-0., -0., -0., 1.],
        [1., 1., 1., 1.]])
tensor([[-1., -1., -1.,  0.],
        [ 0.,  0.,  0.,  0.]])
tensor([[-0.0886, -0.5000, -0.5000,  0.5000],
        [ 0.5000,  0.4310,  0.5000,  0.5000]])

Sin and arcsin:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Aggregate ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vektor & Matriks:
tensor([ 0.,  0., -1.])
tensor([[0.4261, 0.9758],
        [0.4005, 0.7561]])
tensor([[1.2783, 2.9274],
        [1.2015, 2.2684]])
torch.return_types.svd(
U=tensor([[-0.7797, -0.6262],
        [-0.6262,  0.7797]]),
S=tensor([4.0951, 0.1508]),
V=tensor([[-0.4271,  0.9042],
        [-0.9042, -0.4271]]))


**Salin Tensor**

In [31]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # ubah a...
print(b)       # ...dan b otomatis berubah

tensor([[  1., 561.],
        [  1.,   1.]])


In [32]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # objek yang berbeda di memori...
print(torch.eq(a, b))  # ...tapi kontennya masih sama

a[0][1] = 561          # a berubah...
print(b)               # ...tapi b masih sama

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [33]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.1049, 0.8868],
        [0.5399, 0.5126]], requires_grad=True)
tensor([[0.1049, 0.8868],
        [0.5399, 0.5126]], grad_fn=<CloneBackward0>)
tensor([[0.1049, 0.8868],
        [0.5399, 0.5126]])
tensor([[0.1049, 0.8868],
        [0.5399, 0.5126]], requires_grad=True)


**Merubah Dimensi Tensor**

In [34]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [36]:
a = torch.rand(20)
print(a.shape)
print(a)

a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([20])
tensor([0.5428, 0.5758, 0.6952, 0.9356, 0.5503, 0.7245, 0.9691, 0.4227, 0.5589,
        0.1048, 0.4725, 0.5733, 0.7904, 0.0744, 0.2618, 0.4335, 0.1243, 0.8726,
        0.2969, 0.6146])
torch.Size([1, 20])
tensor([[0.8086, 0.1415, 0.7564, 0.4976, 0.1316, 0.1620, 0.8207, 0.8013, 0.3747,
         0.9467, 0.9074, 0.9032, 0.6714, 0.4825, 0.0988, 0.3984, 0.3111, 0.2896,
         0.1643, 0.0897]])
torch.Size([20])
tensor([0.8086, 0.1415, 0.7564, 0.4976, 0.1316, 0.1620, 0.8207, 0.8013, 0.3747,
        0.9467, 0.9074, 0.9032, 0.6714, 0.4825, 0.0988, 0.3984, 0.3111, 0.2896,
        0.1643, 0.0897])
torch.Size([2, 2])
torch.Size([2, 2])


In [38]:
a = torch.ones(4, 3, 2)
print(a.shape)
b = torch.rand(   3)     # perkalian a * b akan menghasilkan runtime error
print(b.shape)
c = b.unsqueeze(1)       # ubah menjadi 2-dimensional tensor, tambahkan dimensi baru
print(c.shape)
print(a * c)             

torch.Size([4, 3, 2])
torch.Size([3])
torch.Size([3, 1])
tensor([[[0.9041, 0.9041],
         [0.8075, 0.8075],
         [0.3982, 0.3982]],

        [[0.9041, 0.9041],
         [0.8075, 0.8075],
         [0.3982, 0.3982]],

        [[0.9041, 0.9041],
         [0.8075, 0.8075],
         [0.3982, 0.3982]],

        [[0.9041, 0.9041],
         [0.8075, 0.8075],
         [0.3982, 0.3982]]])


In [39]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [40]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


**Notasi Einstein**

In [43]:
print(torch.einsum('ii', torch.randn(4, 4)))

print(torch.einsum('ii->i', torch.randn(4, 4)))

x = torch.randn(5)
y = torch.randn(4)
print(x.shape)
print(y.shape)
print(torch.einsum('i,j->ij', x, y))

As = torch.randn(3,2,5)
Bs = torch.randn(3,5,4)
torch.einsum('bij,bjk->bik', As, Bs)



torch.einsum(As, [..., 0, 1], Bs, [..., 1, 2], [..., 0, 2])



A = torch.randn(2, 3, 4, 5)
torch.einsum('...ij->...ji', A).shape

A = torch.randn(3,5,4)
l = torch.randn(2,5)
r = torch.randn(2,4)
torch.einsum('bn,anm,bm->ba', l, A, r)

tensor(2.7848)
tensor([-0.4093,  0.7656,  1.1183,  0.0379])
torch.Size([5])
torch.Size([4])
tensor([[ 2.0492,  3.0784, -3.1240, -2.1338],
        [-0.9036, -1.3575,  1.3776,  0.9410],
        [-0.5572, -0.8371,  0.8495,  0.5802],
        [ 0.6429,  0.9658, -0.9801, -0.6694],
        [-1.1769, -1.7679,  1.7941,  1.2255]])


tensor([[ 7.6319, -3.8703,  6.1122],
        [ 5.3610, -0.9661,  3.2594]])

**Soal**

Hitunglah Perkalian Matriks dengan Menggunakan Notasi Einstein

Bandingkan dengan perkalian matriks biasa

In [44]:
A = torch.randn(7,8)
B = torch.randn(8,9)
C = torch.randn(9,7)
#M = ABC


**Jawaban**

Perkalian matriks

In [57]:
A@B@C

tensor([[ -4.8907,  19.0467,  -8.4887, -18.6290,   3.3187,   5.7778,  -0.7700],
        [ -5.1316,  20.0362, -16.3557,  -4.5188,  -2.7962,   9.5098,   5.3980],
        [  8.5892, -10.7318,  13.5154,  -2.9142,   4.1777,  -7.9839,  -6.2101],
        [ -0.6998,   2.7078,  -0.5010,  -2.1736,  -0.9383,   3.6079,  -1.3929],
        [-11.1672,   7.4879, -11.9979,   6.1631,  -9.4323,  -2.2503,   3.6017],
        [ -3.1706,  -7.7511,   9.5430,  -9.4735,   4.1844, -13.3774,  -7.5693],
        [ -0.6503,   6.5861,  -2.9917,  -1.6711,  -4.5227,  -1.6396,  -0.8229]])

In [58]:
A.matmul(B.matmul(C))

tensor([[ -4.8907,  19.0467,  -8.4887, -18.6290,   3.3187,   5.7778,  -0.7700],
        [ -5.1316,  20.0362, -16.3557,  -4.5188,  -2.7962,   9.5098,   5.3980],
        [  8.5892, -10.7318,  13.5154,  -2.9142,   4.1777,  -7.9839,  -6.2101],
        [ -0.6998,   2.7078,  -0.5010,  -2.1736,  -0.9383,   3.6079,  -1.3929],
        [-11.1672,   7.4879, -11.9979,   6.1631,  -9.4323,  -2.2503,   3.6017],
        [ -3.1706,  -7.7511,   9.5430,  -9.4735,   4.1844, -13.3774,  -7.5693],
        [ -0.6503,   6.5862,  -2.9917,  -1.6711,  -4.5227,  -1.6396,  -0.8229]])

Notasi Einstein

In [59]:
torch.einsum('ab,bc,cd->ad', A, B, C)

tensor([[ -4.8907,  19.0467,  -8.4887, -18.6290,   3.3187,   5.7778,  -0.7700],
        [ -5.1316,  20.0362, -16.3557,  -4.5188,  -2.7962,   9.5098,   5.3980],
        [  8.5892, -10.7318,  13.5154,  -2.9142,   4.1777,  -7.9839,  -6.2101],
        [ -0.6998,   2.7078,  -0.5010,  -2.1736,  -0.9383,   3.6079,  -1.3929],
        [-11.1672,   7.4879, -11.9979,   6.1631,  -9.4323,  -2.2503,   3.6017],
        [ -3.1706,  -7.7511,   9.5430,  -9.4735,   4.1844, -13.3774,  -7.5693],
        [ -0.6503,   6.5861,  -2.9917,  -1.6711,  -4.5227,  -1.6396,  -0.8229]])

Perkalian elemen

In [60]:
A*A

tensor([[3.3245e+00, 2.9495e+00, 7.2840e-04, 9.6540e-01, 4.4290e-01, 1.3487e+00,
         9.9086e-01, 7.9435e-02],
        [1.7586e-01, 2.3237e-01, 2.7851e-01, 4.4492e-01, 8.7332e-01, 4.6912e-01,
         1.5291e+00, 6.5817e-01],
        [2.1471e-01, 5.7510e-01, 9.0035e-01, 1.1497e-01, 1.5771e-02, 2.3843e-01,
         8.1236e-01, 2.5526e-01],
        [2.8154e-02, 1.1258e-02, 4.9704e-01, 1.9787e+00, 2.7034e-01, 1.4352e+00,
         7.6338e-01, 8.8419e-01],
        [1.3784e-01, 1.3857e-01, 2.1353e-01, 8.9445e-01, 3.2477e+00, 1.0775e+00,
         2.3351e-01, 1.6128e-01],
        [1.7577e+00, 9.0954e-03, 1.1220e+00, 1.7703e+00, 8.6338e-01, 7.2983e-01,
         9.5527e-01, 1.6101e-01],
        [1.5263e-02, 1.8128e-01, 3.1681e-01, 3.5090e+00, 1.3644e+00, 7.8231e-02,
         6.3967e-01, 3.4126e+00]])

In [61]:
A.mul(A)

tensor([[3.3245e+00, 2.9495e+00, 7.2840e-04, 9.6540e-01, 4.4290e-01, 1.3487e+00,
         9.9086e-01, 7.9435e-02],
        [1.7586e-01, 2.3237e-01, 2.7851e-01, 4.4492e-01, 8.7332e-01, 4.6912e-01,
         1.5291e+00, 6.5817e-01],
        [2.1471e-01, 5.7510e-01, 9.0035e-01, 1.1497e-01, 1.5771e-02, 2.3843e-01,
         8.1236e-01, 2.5526e-01],
        [2.8154e-02, 1.1258e-02, 4.9704e-01, 1.9787e+00, 2.7034e-01, 1.4352e+00,
         7.6338e-01, 8.8419e-01],
        [1.3784e-01, 1.3857e-01, 2.1353e-01, 8.9445e-01, 3.2477e+00, 1.0775e+00,
         2.3351e-01, 1.6128e-01],
        [1.7577e+00, 9.0954e-03, 1.1220e+00, 1.7703e+00, 8.6338e-01, 7.2983e-01,
         9.5527e-01, 1.6101e-01],
        [1.5263e-02, 1.8128e-01, 3.1681e-01, 3.5090e+00, 1.3644e+00, 7.8231e-02,
         6.3967e-01, 3.4126e+00]])

Notasi Einstein

In [62]:
torch.einsum('ij,ij->ij', A, A)

tensor([[3.3245e+00, 2.9495e+00, 7.2840e-04, 9.6540e-01, 4.4290e-01, 1.3487e+00,
         9.9086e-01, 7.9435e-02],
        [1.7586e-01, 2.3237e-01, 2.7851e-01, 4.4492e-01, 8.7332e-01, 4.6912e-01,
         1.5291e+00, 6.5817e-01],
        [2.1471e-01, 5.7510e-01, 9.0035e-01, 1.1497e-01, 1.5771e-02, 2.3843e-01,
         8.1236e-01, 2.5526e-01],
        [2.8154e-02, 1.1258e-02, 4.9704e-01, 1.9787e+00, 2.7034e-01, 1.4352e+00,
         7.6338e-01, 8.8419e-01],
        [1.3784e-01, 1.3857e-01, 2.1353e-01, 8.9445e-01, 3.2477e+00, 1.0775e+00,
         2.3351e-01, 1.6128e-01],
        [1.7577e+00, 9.0954e-03, 1.1220e+00, 1.7703e+00, 8.6338e-01, 7.2983e-01,
         9.5527e-01, 1.6101e-01],
        [1.5263e-02, 1.8128e-01, 3.1681e-01, 3.5090e+00, 1.3644e+00, 7.8231e-02,
         6.3967e-01, 3.4126e+00]])