
Tensor
==========================

Di Pytorch, tensor digunakan untuk input, output, dan parameter dari sebuah model
Tensor memiliki kelebihan dibanding `NumPy <https://numpy.org/>` dalam 2 hal:
1. Operasi Tensor dapat dihitung melalui GPU
2. Tensor dapat melakukan diferensiasi otomatis (dibahas di pertemuan berikutnya)


In [1]:
import torch
import math
import numpy as np

**Inisiasi sebuah Tensor**

Tensor dapat diinisiasi melalui beragam cara

**Langsung dari data**

Tensor dapat diciptakan langsung dari data


In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**Dari sebuah NumPy array**

Tensor dapat diciptakan langsung dari Numpy arrays (dan sebaliknya)



In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**Dari Tensor yang lain:**

Tensor yang baru akan memiliki sifat (shape, datatype) dari tensor sebelumnya, kecuali secara explicit diganti.



In [4]:
x_ones = torch.ones_like(x_data) # mempertahankan sifat x_data
print(f"Ones Tensor: \n {x_ones} \n")

#x_rand = torch.rand_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float) # mengganti dtype x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8801, 0.4443],
        [0.1016, 0.5518]]) 



**Dari sebuah angka random atau konstanta:**

``shape`` adalah sebuah tuple dari dimensi tensor. Itu akan menentukan dimensi dari tensor output pada fungsi di bawah ini.



In [5]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5959, 0.1223, 0.4728],
        [0.6117, 0.9135, 0.5143]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




**Attributes of a Tensor**

Atribut Tensor akan menjelaskan bentuk, tipe data, dan perangkat penyimpanan tensor



In [6]:
tensor = torch.rand(3,4)
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.9026, 0.5402, 0.2460, 0.6025],
        [0.9929, 0.4689, 0.3872, 0.4815],
        [0.3308, 0.5997, 0.1813, 0.7099]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




**Operasi pada Tensor**

Terdapat lebih dari 100 operasi tensor (termasuk aritmatika, aljabar linear, manipulasi matriks, dan lainnya), dijelaskan secara lebih komprehensif `disini <https://pytorch.org/docs/stable/torch.html>`

Setiap operasi ini dapat dioperasikan di GPU. Jika menggunakan Colab, alokasikan sebuah GPU melalui Runtime > Change runtime type > GPU

Secara bawaan, tensor diciptakan pada CPU. Kita harus memindahkan tensor ke GPU menggunakan metode ``.to`` (setelah memeriksa ketersediaan GPU). Memindahkan tensor besar antar perangkat, dapat memakan waktu dan memori yang banyak (jadi rencanakanlah secara hati-hati !!!)


In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('Bisa GPU')
    tensor = tensor.to('cuda')
else:
    print('Hanya bisa CPU')

Hanya bisa CPU


Coba beberapa operasi dari daftar.



**Operasi standard yang mirip numpy untuk indexing dan slicing:**



In [8]:
tensor = torch.ones(4, 4)
print('Baris pertama: ', tensor[0])
print('Kolom pertama: ', tensor[:, 0])
print('Kolom terakhir:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

Baris pertama:  tensor([1., 1., 1., 1.])
Kolom pertama:  tensor([1., 1., 1., 1.])
Kolom terakhir: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Menyatukan beberapa tensor** 

Gunakan ``torch.cat`` untuk concatenate beberapa tensor secara pilihan dimensi.
Alternatif lain, `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,



In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Operasi Aritmatika**



In [10]:
print(tensor)
# Menghitung perkalian matriks antara 2 tensors. y1, y2, y3 akan memiliki nilai yang sama
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(tensor)
print(torch.matmul(tensor, tensor.T, out=y3))

# Menghitung perkalian elemen. z1, z2, z3 akan memiliki nilai yang sama
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**tensor 1-elemen** Jika memiliki sebuah tensor 1-elemen (contoh: agregat semua nilai dari sebuah tensor menjadi 1 angka), itu dapat diubah menjadi python numerik menggunakan ``item()``:



In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**Operasi In-Place**

Operasi yang menyimpan hasil kedalam variabel itu sendiri disebut in-place. Mereka menggunakan imbuhan ``_``

contoh: ``x.copy_(y)``, ``x.t_()``, akan merubah ``x``.



In [12]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div class="alert alert-info"><h4>Catatan</h4><p>Operasi In-place dapat menimbulkan masalah ketika menghitung turunan karena kehilangan sejarah operasi. Jadi penggunaan seperti ini kurang dianjurkan.</p></div>



--------------




**Jembatan dengan Numpy**

Tensor pada CPU dan Numpy array dapat menggunakan lokasi memori yang sama,
merubah yang satu akan merubah yang lain




Tensor menjadi NumPy array



In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Perubahan pada tensor terjadi pada Numpy array.



In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array menjadi Tensor



In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Perubahan pada Numpy array terjadi pada Tensor.



In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


**Matematika dan Logika dengan Tensor**

In [17]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [18]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


**Tensor Broadcasting**

Aturan Broadcasting:
- Masing-masing tensor paling sedikit harus memiliki 1 dimensi
- Membandingkan dimensi dari 2 tensors, dari yang akhir ke yang pertama:
    - Masing-masing dimensi harus sama, atau
    - Salah satu dimensi harus ukuran 1, atau
    - Dimensi tidak eksis di salah satu tensor


In [19]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.8368, 0.2670, 0.8889, 0.3817],
        [0.5358, 0.7921, 0.3178, 0.1628]])
tensor([[1.6735, 0.5340, 1.7779, 0.7635],
        [1.0717, 1.5842, 0.6356, 0.3256]])


In [20]:
a =     torch.ones(4, 3, 2)
print(a)

b = a * torch.rand(   3, 2) # dimensi ke 3 dan 2 identik dengan a, # dimensi ke 1 absen
print(b)

c = a * torch.rand(   3, 1) # dimensi ke 3 = 1, # dimensi ke 2 identik dengan a
print(c)

d = a * torch.rand(   1, 2) # dimensi ke 3 identik dengan a, # dimensi ke 2 = 1
print(d)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.2289, 0.6012],
         [0.7730, 0.5474],
         [0.5457, 0.7708]],

        [[0.2289, 0.6012],
         [0.7730, 0.5474],
         [0.5457, 0.7708]],

        [[0.2289, 0.6012],
         [0.7730, 0.5474],
         [0.5457, 0.7708]],

        [[0.2289, 0.6012],
         [0.7730, 0.5474],
         [0.5457, 0.7708]]])
tensor([[[0.6323, 0.6323],
         [0.3425, 0.3425],
         [0.7504, 0.7504]],

        [[0.6323, 0.6323],
         [0.3425, 0.3425],
         [0.7504, 0.7504]],

        [[0.6323, 0.6323],
         [0.3425, 0.3425],
         [0.7504, 0.7504]],

        [[0.6323, 0.6323],
         [0.3425, 0.3425],
         [0.7504, 0.7504]]])
tensor([[[0.3445, 0.0517],
         [0.3445, 0.0517],
         [0.3445, 0.0517]],

        [[0.3445,

**Matematika Tensor Lanjutan**

In [21]:
# fungsi umum
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# fungsi trigonometri dan inversnya
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSin and arcsin:')
print(angles)
print(sines)
print(inverses)

# operasi bitwise
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# perbandingan:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # pembanding
print(torch.eq(d, e)) # returns sebuah tensor tipe bool

# aggregasi:
print('\nAggregate ops:')
print(torch.max(d))        # returns sebuah 1-elemen tensor
print(torch.max(d).item()) # mengeluarkan nilai dari tensor
print(torch.mean(d))       # rata-rata
print(torch.std(d))        # standard deviasi
print(torch.prod(d))       # perkalian semua angka
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter elemen unik

# vektor dan aljabar linear
v1 = torch.tensor([1., 0., 0.])         # unit vektor x
v2 = torch.tensor([0., 1., 0.])         # unit vektor y
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # 3x I

print('\nVektor & Matriks:')
print(torch.cross(v2, v1)) # -ve dari unit vektor z (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3x m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.2815, 0.6217, 0.5558, 0.8532],
        [0.4609, 0.0221, 0.9688, 0.2004]])
tensor([[-0., 1., 1., -0.],
        [1., 1., 1., -0.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0.,  0.,  0., -1.]])
tensor([[-0.2815,  0.5000,  0.5000, -0.5000],
        [ 0.4609,  0.0221,  0.5000, -0.2004]])

Sin and arcsin:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Aggregate ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vektor & Matriks:
tensor([ 0.,  0., -1.])
tensor([[0.1296, 0.9481],
        [0.5737, 0.8284]])
tensor([[0.3888, 2.8442],
        [1.7211, 2.4852]])
torch.return_types.svd(
U=tensor([[-0.6863, -0.7273],
        [-0.7273,  0.6863]]),
S=tensor([4.0547, 0.9690]),
V=tensor([[-0.3745,  0.9272],
        [-0.9272, -0.3745]]))


**Salin Tensor**

In [22]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # ubah a...
print(b)       # ...dan b otomatis berubah

tensor([[  1., 561.],
        [  1.,   1.]])


In [23]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # objek yang berbeda di memori...
print(torch.eq(a, b))  # ...tapi kontennya masih sama

a[0][1] = 561          # a berubah...
print(b)               # ...tapi b masih sama

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [24]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.8820, 0.7883],
        [0.2963, 0.2949]], requires_grad=True)
tensor([[0.8820, 0.7883],
        [0.2963, 0.2949]], grad_fn=<CloneBackward0>)
tensor([[0.8820, 0.7883],
        [0.2963, 0.2949]])
tensor([[0.8820, 0.7883],
        [0.2963, 0.2949]], requires_grad=True)


**Merubah Dimensi Tensor**

In [25]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [26]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.3853, 0.1668, 0.3821, 0.2608, 0.1302, 0.2329, 0.0026, 0.9248, 0.0931,
         0.2650, 0.4897, 0.4584, 0.1247, 0.3229, 0.9680, 0.5080, 0.8286, 0.8318,
         0.5977, 0.1586]])
torch.Size([20])
tensor([0.3853, 0.1668, 0.3821, 0.2608, 0.1302, 0.2329, 0.0026, 0.9248, 0.0931,
        0.2650, 0.4897, 0.4584, 0.1247, 0.3229, 0.9680, 0.5080, 0.8286, 0.8318,
        0.5977, 0.1586])
torch.Size([2, 2])
torch.Size([2, 2])


In [27]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # perkalian a * b akan menghasilkan runtime error
c = b.unsqueeze(1)       # ubah menjadi 2-dimensional tensor, tambahkan dimensi baru
print(c.shape)
print(a * c)             

torch.Size([3, 1])
tensor([[[0.8999, 0.8999],
         [0.6499, 0.6499],
         [0.1299, 0.1299]],

        [[0.8999, 0.8999],
         [0.6499, 0.6499],
         [0.1299, 0.1299]],

        [[0.8999, 0.8999],
         [0.6499, 0.6499],
         [0.1299, 0.1299]],

        [[0.8999, 0.8999],
         [0.6499, 0.6499],
         [0.1299, 0.1299]]])


In [28]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [29]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


**Notasi Einstein**

In [30]:
print(torch.einsum('ii', torch.randn(4, 4)))

print(torch.einsum('ii->i', torch.randn(4, 4)))

x = torch.randn(5)
y = torch.randn(4)
print(torch.einsum('i,j->ij', x, y))

As = torch.randn(3,2,5)
Bs = torch.randn(3,5,4)
print(torch.einsum('bij,bjk->bik', As, Bs))



print(torch.einsum(As, [..., 0, 1], Bs, [..., 1, 2], [..., 0, 2]))



A = torch.randn(2, 3, 4, 5)
print(torch.einsum('...ij->...ji', A).shape)

A = torch.randn(3,5,4)
l = torch.randn(2,5)
r = torch.randn(2,4)
print(torch.einsum('bn,anm,bm->ba', l, A, r))

tensor(-2.6875)
tensor([-0.7363,  0.1423,  0.0993, -1.7870])
tensor([[ 7.3245e-01,  2.8586e-02,  5.9338e-01,  1.2484e+00],
        [ 8.9689e-01,  3.5004e-02,  7.2659e-01,  1.5287e+00],
        [-2.7772e-01, -1.0839e-02, -2.2499e-01, -4.7337e-01],
        [-2.7699e-03, -1.0811e-04, -2.2440e-03, -4.7212e-03],
        [ 6.0250e-01,  2.3514e-02,  4.8809e-01,  1.0269e+00]])
tensor([[[-4.6102, -3.6538, -3.0413, -2.2825],
         [ 1.7455, -0.1091,  3.2850,  1.5766]],

        [[-0.2434,  1.1855,  3.2531, -1.8979],
         [ 2.6340, -3.1533,  3.0218,  1.3617]],

        [[-1.1219,  1.7622, -2.5509, -0.7482],
         [ 0.9646,  2.6877,  2.0141,  3.0457]]])
tensor([[[-4.6102, -3.6538, -3.0413, -2.2825],
         [ 1.7455, -0.1091,  3.2850,  1.5766]],

        [[-0.2434,  1.1855,  3.2531, -1.8979],
         [ 2.6340, -3.1533,  3.0218,  1.3617]],

        [[-1.1219,  1.7622, -2.5509, -0.7482],
         [ 0.9646,  2.6877,  2.0141,  3.0457]]])
torch.Size([2, 3, 5, 4])
tensor([[-3.5017,  0.3813, 

**Soal**

Hitunglah Perkalian Matriks dengan Menggunakan Notasi Einstein

Bandingkan dengan perkalian matriks biasa

In [31]:
A = torch.randn(7,8)
B = torch.randn(8,9)
C = torch.randn(9,7)
#M = AB
